pull_request_rules: []
commands_restrictions:
  queue:
    conditions:
      - sender-permission >= write
queue_rules:
  - name: default
    queue_conditions: []
    merge_conditions:
      - check-success = vm6-freeze-ci
    checks_timeout: null
merge_protections:
  - name: VM6 Freeze Enforcement Baseline
    if: []
    success_conditions:
      - base = main
merge_protections_settings:
  reporting_method: check-runs
  post_comment: true
